name: Analyse SonarQube reconning

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: self-hosted
    timeout-minutes: 20

    permissions:
      contents: read

    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/*.java','**/*.js','**/*.ts','**/*.php','**/*.cs','**/*.py','**/*.go','**/*.xml') }}
          restore-keys: |
            sonar-${{ runner.os }}-

      - name: Debug SONAR_HOST_URL
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          echo "SONAR_HOST_URL=>>${SONAR_HOST_URL}<<"
          printf "%s" "${SONAR_HOST_URL}" | hexdump -C | tail -n+1

      - name: Preflight /batch/index
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          set -euo pipefail
          command -v jq >/dev/null || sudo apt-get update && sudo apt-get install -y jq
          echo "HEAD ${SONAR_HOST_URL%/}/batch/index"
          curl -kI "${SONAR_HOST_URL%/}/batch/index"
          echo "Status API:"
          curl -ks "${SONAR_HOST_URL%/}/api/system/status" | jq .

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=sonar-test
            -Dsonar.projectName=Test-SonarQube-depuis-GitHub
            -Dsonar.sources=.
            -Dsonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
