name: Analyse SonarQube

on:
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

concurrency:
  group: sonar-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonar:
    name: SonarQube Analysis
    # Ajoute tes labels runner si nécessaire : [self-hosted, linux, sonar]
    runs-on: self-hosted
    timeout-minutes: 20

    permissions:
      contents: read

    env:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Java requis car le scanner tourne sur une JVM
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Sonar packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('**/*') }}
          restore-keys: sonar-${{ runner.os }}-

      # Pré-check connectivité vers SonarQube (ignore cert auto-signé)
      - name: Preflight SonarQube
        run: |
          set -euxo pipefail
          command -v curl || (sudo apt-get update && sudo apt-get install -y curl jq)
          echo "HEAD ${SONAR_HOST_URL}/batch/index"
          curl -kI "${SONAR_HOST_URL}/batch/index"
          echo "Status API:"
          curl -ks "${SONAR_HOST_URL}/api/system/status" | jq .

      # --- build/tests/coverage à adapter selon ta stack ---
      # - run: mvn -B verify
      # - run: npm ci && npm test -- --coverage
      # - run: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=sonar-test
            -Dsonar.projectName=Test-SonarQube-depuis-GitHub
            -Dsonar.sources=.
            -Dsonar.exclusions=**/vendor/**,**/node_modules/**,**/dist/**,**/build/**
            -Dsonar.scanner.skipCertificateCheck=true
            # Exemple (décommente/ajuste selon ta stack) :
            # -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            # -Dsonar.php.coverage.reportPaths=build/logs/clover.xml
            # -Dsonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

      - name: SonarQube Quality Gate
        # Pour ignorer le cert auto-signé côté action Node (appel API), on désactive la vérif TLS ici
        env:
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        uses: SonarSource/sonarqube-quality-gate-action@v1
        # with:
        #   timeout-minutes: 15  # optionnel: délai d'attente du Quality Gate